### ISSUE TITLE
How to increase depth?

### ISSUE THREAD

**Issue by acubino** [RBEGamer/K3_LASER_ENGRAVER_PROTOCOL#1]
Im engraving anodized aluminium, and i need to do 5 passes in order to mark.

How can be the best way to doy?. the depth max is 200, and i suppose is comunication limit and i can't change by software.
Maybe, send the same line more than 1 time?. Or the only solution is made the complete job some times?

**Comment by RBEGamer** [comment]
Yes i think this is possible. If you engrave every time from the home position, you can run the script X times to increase the depth.
Maybe its possible to send the command more than one time but i dont know it the laser accept this.

The send is in line `499` in the `main.cpp`, i think its easy to put this in a for loop so its easy to modify:

`if(is_line_white ){
            _ser.Write(img_line_buffer,ilbsize);//SEND BUFFER TO ENGRAVER
            wait_for_ack(_ser);
            std::cout << "progress_" << current_height_progress <<std::endl;
            thread_sleep(100);
        }`

**Comment by acubino** [comment]
Yes, i made this change and works like a charm.
Why _engraving_depth_intensity max is 200?. I change to 255 and works ok.

**Comment by RBEGamer** [comment]
I added the passes option to the code, There is a passes switch to set the passes now.
Yes 255 works fine too, the original software has this slider from 1-200.
But i noticed no much difference between 200 and 255.
