### ISSUE TITLE
Not starting correctly second job

### ISSUE THREAD

**Issue by acubino** [RBEGamer/K3_LASER_ENGRAVER_PROTOCOL#2]
I have a issue, that not happen all times.

I send a job, it prints correctly. Job finish, my machine still connected to computer and powered.
I send a second job, it starts to print a line when connect (like some still in buffer), and machine start printing in finish line. They don't go to home or reset position.

If i unplug the power supply and redo, it works ok, only if between jobs. 

Maybe a disconect o reset is needed when job are finish?

**Comment by RBEGamer** [comment]
hmm not all times ? Can you specify in which cases it happens ?
Are you simply start the program again (in a shell file) or did you call the `start_rengraving` multible times ? You cant try to call the `send_reset_command ` after the `start_rengraving ` call maybe with a delay.
